
answer:
	go run demo/pion-to-pion/answer/main.go --offer-address 0.0.0.0:8080 --answer-address 0.0.0.0:8081

offer:
	go run demo/pion-to-pion/offer/main.go --offer-address localhost:8080 --answer-address localhost:8081